#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/ProjectSakura/android.git -b 10 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Sync device tree vendor & kernel sauce
git clone https://github.com/Gabuters-Dev/device_xiaomi_ugglite -b lineage-17.1-rebase device/xiaomi/ugglite
git clone https://github.com/Gabuters-Dev/vendor_xiaomi_ugglite -b lineage-17.1-rebase vendor/xiaomi
git clone https://github.com/Gabuters-Dev/kernel_xiaomi_msm8917 -b gabut-ten kernel/xiaomi/msm8917
